# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  url: postgresql://postgres:GoLJeO1KFV80bJISy548@containers-us-west-146.railway.app:6775/railway
  database: railway
  username: postgres
  password: GoLJeO1KFV80bJISy548
  host: containers-us-west-146.railway.app
  port: 6775
  pool: 5
